/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppSubjectsRouteImport } from './routes/app.subjects'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNoticesRouteImport } from './routes/app.notices'
import { Route as AppMarksRouteImport } from './routes/app.marks'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppDepartmentsRouteImport } from './routes/app.departments'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppUsersUserIdRouteImport } from './routes/app.users.$userId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksRoute = AppMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/marks': typeof AppMarksRoute
  '/app/notices': typeof AppNoticesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subjects': typeof AppSubjectsRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/app/users/$userId': typeof AppUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/departments'
    | '/app/fees'
    | '/app/marks'
    | '/app/notices'
    | '/app/profile'
    | '/app/subjects'
    | '/app/timetable'
    | '/app/users'
    | '/app/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/departments'
    | '/app/fees'
    | '/app/marks'
    | '/app/notices'
    | '/app/profile'
    | '/app/subjects'
    | '/app/timetable'
    | '/app/users'
    | '/app/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/departments'
    | '/app/fees'
    | '/app/marks'
    | '/app/notices'
    | '/app/profile'
    | '/app/subjects'
    | '/app/timetable'
    | '/app/users'
    | '/app/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subjects': {
      id: '/app/subjects'
      path: '/subjects'
      fullPath: '/app/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notices': {
      id: '/app/notices'
      path: '/notices'
      fullPath: '/app/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks': {
      id: '/app/marks'
      path: '/marks'
      fullPath: '/app/marks'
      preLoaderRoute: typeof AppMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/$userId': {
      id: '/app/users/$userId'
      path: '/$userId'
      fullPath: '/app/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersUserIdRoute: AppUsersUserIdRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppMarksRoute: typeof AppMarksRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppFeesRoute: AppFeesRoute,
  AppMarksRoute: AppMarksRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
