/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppNoticesRouteImport } from './routes/_app.notices'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppNoticesRoute = AppNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/fees': typeof AppFeesRoute
  '/notices': typeof AppNoticesRoute
  '/timetable': typeof AppTimetableRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/fees': typeof AppFeesRoute
  '/notices': typeof AppNoticesRoute
  '/timetable': typeof AppTimetableRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/notices': typeof AppNoticesRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/fees'
    | '/notices'
    | '/timetable'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/departments'
    | '/fees'
    | '/notices'
    | '/timetable'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/fees'
    | '/_app/notices'
    | '/_app/timetable'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notices': {
      id: '/_app/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AppNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppNoticesRoute: typeof AppNoticesRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppFeesRoute: AppFeesRoute,
  AppNoticesRoute: AppNoticesRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
